BSSAVEHISTPP_DECAYLENGTH=1
BSSAVEHISTPBPB_DECAYLENGTH=0

BSFITPP_DECAYLENGTH=1
BSFITPBPB_DECAYLENGTH=0

INPUTDATAPP=""
INPUTMCPP=""

TRGPP=""
TRGPPMC=""

FILTERCUTPP="abs(PVz)<15&&pBeamScrapingFilter&&pPAprimaryVertexFilter&&TMath::Abs(By)<2.4&&TMath::Abs(Bmumumass-3.096916)<0.15&&Bmass>5&&Bmass<6"
FILTERCUTPP_FIDUCIAL=""

#### Saving histograms
if [ $BSSAVEHISTPP_DECAYLENGTH -eq 1 ]; then
g++ saveMasshisto.C $(root-config --cflags --libs) -g -o saveMasshisto.exe
./saveMasshisto.exe "$INPUTDATAPP" "$INPUTMCPP" "$TRGPP" "${FILTERCUTPP}&&${FILTERCUTPP_FIDUCIAL}&&${ADDCUTPP_DECAYLENGTH}" "$ISMCPP" "1" "$LABELPP" "$NOMINALPP_DECAYLENGTH" "$LABEL_DECAYLENGTH" "$VAR_DECAYLENGTH" "$VARBINS" "$VARMIN_DECAYLENGTH" "$VARMAX_DECAYLENGTH" "$VARVAL_DECAYLENGTH" "$VARSIGN_DECAYLENGTH" "$PTTHRESHOLEPP"
